import type { Metadata } from 'next';
import { manrope } from './fonts';
import 'modern-normalize';
import './globals.css';
import Header from '@/components/Header/Header';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import Container from '@/components/Container/Container';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.variable}>
        <TanStackProvider>
          <Container>
            <Header />
            <main>{children}</main>
          </Container>
        </TanStackProvider>
      </body>
    </html>
  );
}
